#!/usr/bin/env bash

startTimeSeconds=$(echo $1 | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 }')
stopTimeSeconds=$(echo $2 | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 }')

videoDurationSeconds=$((stopTimeSeconds - startTimeSeconds))

echo -H start-at=duration:$startTimeSeconds -H stop-at=duration:$videoDurationSeconds
